# Generated by Django 4.0.4 on 2022-11-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_categorybrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categorybrand',
            options={'verbose_name': 'Бренды', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Граммы', 'verbose_name_plural': 'Граммы'},
        ),
    ]
