# Generated by Django 4.0.4 on 2022-11-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='all_price',
            field=models.FloatField(default=0),
        ),
    ]
