# Generated by Django 4.0.4 on 2022-11-20 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartitem_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 18, 43, 0, 7879)),
        ),
    ]
