# Generated by Django 4.0.4 on 2022-11-20 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 19, 16, 41, 371560)),
        ),
    ]
